services:
  db:
    image: postgres:16
    container_name: shopping-list-db
    environment:
      POSTGRES_DB: shopping_list
      POSTGRES_USER: shopping_list
      POSTGRES_PASSWORD: shopping_list
    ports:
      - "5432:5432"
    volumes:
      - shopping_list_db_data:/var/lib/postgresql/data

volumes:
  shopping_list_db_data:
